language: python
python:
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y openssl
install:
  - pip install --upgrade pip
  - pip install -e .[testing]
script:
  - pycodestyle cum
  - nose2 --verbose
deploy:
  provider: pypi
  user: cumbottler
  password:
    secure: 74h3/CN0Bk71B5OepjQ5oC/VUzRKESZIccB97mRkJnjY9d7NrMBfZfF0l6u3APCshgjM0M9Lbsc0HPYSGf9c/rPGr/WLuQxXBNNrH3simqwPm5Gg3M9iMQAxU9s7C22gZMXT6EmGtpFafBF1t0h0IocwKDN0VY22O1urqJAarIejr6yVurQvTjax16ytQHMnvjpTgTIyH7da/VtMG/7TvV1owxjifQM0Ei7cz9dUPJcAcnBQLoruA0wanrvhLjD+ROkBFPK4xRAp7b2kZzTYG7UEl41Dm0lTDtjLtKM7u+q/8ziXWtGqVpnJuInvUD3lbusXLLRNO7+466cMGHTf3fC59z6rD66/JsB8hhhyFHYqeTFgYc6pvGseMiNU96XHbetKOyQUkx7xIZzwfCrwLN9JjZWRrl81m6NMnAuAQysOlROPuhOyiMXZhytR2Bsy0I/vDHy5ZUKc9mz4nWmpEDTOF4Wqd4F2k6vHU26KKM6UPJLyfDJEnMd9lfzIVLdwmdyt4BL+G8pJc6vmkrdJsef2D+5bQ0v1NvS3Jww7D2Cda30Jz+eMelQN6WB7OI1OwapzGdAlb0nKV63TZGXtSsQcymb3XaRmUe8hMz2UOgzA3qjKBgK4bM9uARbWOz4PoUCz0UY/oczM5LlHFu2YpkSqiRhWxqTr8KGXH+fn0DU=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
notifications:
  irc:
    channels:
      - "irc.rizon.net#cu"
    skip_join: true
    nick: buildslut
after_success:
  - codecov
env:
  global:
  - COLUMNS=80
  - BROWSER=/bin/true
  - secure: 9mAn+2A30iuIIAsh+T1K34tUzKwIk0sz7CV1ookzMuOzTApsvGqPxKL9DO64MzIvVYjHajF/XQgqo9UcUq39p7bUItER882knAh6Ppsq6HUtpj3sv5/ItP1xmqMVlnI5yLBcQBZAEl8L5MWoFyfYfVwv82KzPn3imWcBrGm/6jT6OBq/cyLVG0n0s47ZcL2yLGsUXP9nPajmo2Pfye9tsqmr2+B7nLqY3LPE2c77LhsC1FH2yY0urv+HTmj6fC7xb+3xGliAYOXiEUcb7RXJojEwsACB0yzP3WDMEKlTFH9XarlmqmPuDpek5g3VCDURpsD1wv6pwna7+0i/zhzKqWy93l98vTgGmZMuNkW+qhnbEZ94UaPuoiMad6ICX8X4BDDj8ficNGcAoQFBH1eneKwk5uBsYo4LkA3vB2Mx3daP9rFXtaX1gDE25zIBOZXjAPimWeUyPtMPxtR3XvGD9jY6CIBC+IPlgxn7h+ufznmKqDM/0RmTtraDyuHBqz1BEGct8CvzZNnOepZHArk896AVTlKcfQK/TBo+IrvFUzA3f0ac1yfbBp+bgIBijF4TEWqUH3UFRQSLaxSzDTMB3OVEFt7qEJE3IIYVLlz7OYqKH12hPA7LIMgnPQQri4dCe3fzKosyKFWvg4dZxhYNKTNaqsFHe+sSiz378SBxuBo=
  - secure: cdsKn1NNB5+Mo2AGxoizy9czZJX7WOGQmFJzu9LpaibQzTkPihbLUuA4nbxeFE65eRRsO7NTz3Bru5bAickilhvYt0Fg7MfbpaA3L4QC87ocbJzJp/k/NK3jZx7ImRPNdDpGw8wOJW75juTJMRbx6wSaIL5b2+WUgVSChxN9j8T+dfh1jD2gs/L2cQKjtOFyy28MNp0pS5txlhRvHfb90muXqcrhNiOZrgqnBVxCpj+j1dIiype3N8EOItBgN8thTENYzFHcQCPJ+LYxIvKOWnNxPpkmo9X2RVJ6MHD57LvpiYpHCm8Y7Ja7j9Eze3X7qm+EJFRYDxkUUFqvyo8ikJLmAOHb4gwR/RZkdIwVOAh31Nb7SXlhOwAyiVuTClVzLVXB32DqjxjyCDrcNNxgseTkI20lakcP2n+pq9ZJ0R4svRC8QispLVg2ojw7qKq+CZ6K1RpGKTNDRplGIsiVaSJPWgZC7srUeQvLHoBZYCP5/COQMaI6sOH82Oiuoakl93hhxd5b5jvTstSRWWZ85bxakbsUeCNhgUCTfu3G6G7FIixq5LwL0yJGg8/GUdjWXz7qwG0RKa/BNCxIlhHKW53AQBNPSjaQRua01ebMOSE1DYFfU5hEi89zjFA8Qx+v7r1uxio9Y3TVsFF6r+296eo7mlohVX8xqxhDG9tYpRo=
  - secure: DiODiAC8zP1VfEH75DYEaYgKbPu32GrzukmEZP6K0E23c/MvVxKWfRi9Rj5L5kzv5RehmICQSCL1aEqFnm4SR/pduUz/LkTQl4DRh85HWUJUZVvTKaRkbtzXN9H7a23HX0JL70TF5mJwEMedMvUTUtpfZ/y9gaiJLOZDsY+PrVaUZrzCw/kULAvFbJRnKxzT7m5soEPtNH+pN1BguZlH7M8MBf/gPxUbRmnq6kYFN90nDBHH4FPIbjhR8qbQL4dRgAu67cm4PhSclAkVGo8TkDC5xB3wqb2HgzcwXbNC19t97G93n9h86KyuLkuIdOKUq7UA9QunzFV2Sa58aDyRkLkWVDOpPrd6MulzdgK/2nsQJEjCVt272S/Jq5butnBAd4uFnRfmIk7TCa5NisKf8bluDWaZ2igKkdGdiF+pO6/L1pnSDgdH/etK5qc5hgPZAJZYt9WFTSYhFlPSfXYKF/BN5GzYOj1OTLUIpxJ6dgMbj6dC987/s4PqdBs0K4tcU/6sceOaV/zgrYJWwJws6Jy+obH/kP5m/Uk8esOG0/1mYbnuDyLocUoWVqmGDZWR8H9+lXpiGDiPz3YESZ9hJq5EWndIu9IUQWXsFqlB1ctU7ERONmYIhSs/5IViWLQFwyykLmsyOnrgn/odas9hQkvuX0otJ0u+MnERy+3UODU=
  - secure: goZ4VDik6lTVluA0az9qdB9mFV75iEzgpK2ZGecCGorIsMytkzduatsaIEUBeXJkAoN3QTs8VWb7vz7RcQDErazHVXfjO79MVaO6APiA9NOjDCwiuXd/nSJqx8dXOhcFZp6YIA/asS+tp2fihHi8ebsB2xGTyUoDJXuE9Dn85Kx7d5qNA0Lz4AQZvfU+dvY+CECI++KSWvPX0Zo4FlhC6BI5aDP0HZ1vqN21Gd17cKKZ9jjSDmbxPK8BEDAiEzHq9mlRocAa86Ven5wOVaZRY/g65cCvkSOHoT4KF2HFipHW5dswtMqLNej2MmlrEnYUPJdQv54BLd2pDZ6BJDm1x2arUvT/x1Y4E2icvRK1T5S5PGkhtCCYaEsD5M93QuAvcbHKpqugtm68n3A2I+ns6/YpoXzCXzCgvt0MdWp2B3YW9PQHsH1rwf8jjjfdU5J5N369iEYBqFWX0+Vk3gScjDKfLN4a1vw40t1OCxaLS1OXVMN2Qu21q0GvNFAxPG6p3YKM2g+UjCtVHWsQLMrdtukrHw5ao67sQOBzHO+378Qiw5jGEfmi9tLtKeEFbipPIIa9ExXGJcMSGqC9Dmbkg2p+UYb8g+QxZqBgGrtDfPZVTKVB1TJWFvgO8GA1RkOR0dtcTHU6CwBpTQ9eXuRI5tZDyWy31TwPMkglp8R+krM=
